
# --- CASA ---
db.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
db.user=mxrtin
db.password=Fuckencio420

# --- CLASE ---
#db.url =jdbc:oracle:thin:@//localhost:1521/xe
#db.user =MARTINDAM
#db.password =Fuckencio420
